name: CI
run-name: ${{ github.workflow }}-${{ github.ref_name }}
on: # триггер для запуска workflow
  push: # на запуск workflow при пуше в ветку main
    branches: ["main"]
  pull_request: # на запуск workflow при создании PR в ветку main
    branches: ["main"]

env: # переменные окружения, которые будут доступны во всех шагах
  PYTHON_VERSION: "3.10"
  PYTHON_APP_NAME: "kube2py"

concurrency: # настройка параллельного запуска workflow
  group: ${{ github.workflow }}-${{ github.ref_name }} # группа для параллельного запуска workflow. В данном случае группа будет содержать имя workflow и имя ветки, в которую был сделан пуш.
  cancel-in-progress: true # отмена всех предыдущих запущенных workflow в группе при запуске нового workflow. В данном случае при пуше в ветку main будут отменяться все предыдущие запущенные workflow в группе CI-main.
jobs:
  python-ci: # имя джоба, которое будет отображаться в UI
    strategy: # стратегия для запуска джоба
      matrix: # матрица для запуска джоба на разных версиях Python
        python-version: ["3.10", "3.8"] # версии Python, на которых будет запускаться джоб
        os: [ubuntu-latest, windows-latest] # операционные системы, на которых будет запускаться джоб

    runs-on: ${{ matrix.os }} # используемый образ для запуска джоба
    defaults: # значения по умолчанию для шагов
      run: # значения по умолчанию для шага run
        working-directory: ./src # рабочая директория по дефолту чтобы не прописывать путь к src в каждом шаге

    steps:
      - uses: actions/checkout@v4 # шаг для клонирования репозитория в рабочую директорию
      - uses: actions/setup-python@v6 # шаг для установки Python в рабочую директорию
        name: Setup Python ${{ matrix.python-version }} # имя шага, которое будет отображаться в UI
        with: # параметры для шага setup-python
          python-version: ${{ matrix.python-version }} # версия Python, которую нужно установить

      - name: Install dependencies # шаг для установки зависимостей проекта
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install -r requirements.txt

      - name: Lint with flake8 # шаг для проверки кода на соответствие стандартам PEP8 с помощью flake8.
        # cd ../ - переход в корневую директорию проекта, чтобы учелся файл .flake8 в котором прописаны настройки для flake8
        run: |
          cd ../
          flake8 . --show-source --statistics

      - name: Check Complexity # шаг для проверки сложности кода с помощью flake8
        # cd ../ - переход в корневую директорию проекта, чтобы учелся файл .flake8 в котором прописаны настройки для flake8
        run: |
          cd ../
          flake8 . --exit-zero --max-complexity=10 --statistics

      - name: Test with pytest # шаг для запуска тестов с помощью pytest и генерации отчета о покрытии кода
        run: |
          pytest -v --cov-report=term-missing --cov=. --cov-report=json

      - name: Upload python artifacts # шаг для загрузки артефактов с результатами тестов и покрытия кода
        if: ${{ github.ref_name == 'main' }} # условие для запуска шага только при пуше в ветку main
        uses: actions/upload-artifact@v4
        with: # парамтры для шага upload-artifact
          name: python-artifacts # имя артефакта, который будет отображаться в UI
          path: . # путь к директории с артефактами, которые нужно загрузить

      - name: Upload Helm artifacts
        if: ${{ github.ref_name == 'main' }}
        uses: actions/upload-artifact@v4
        with:
          name: helm-artifacts
          path: ${{ github.workspace }}/helm-charts

  build-docker-image: # имя джоба, которое будет отображаться в UI
    if: ${{ github.ref_name == 'main' }} # условие для запуска джоба только при пуше в ветку main
    runs-on: ubuntu-latest # используемый образ для запуска джоба
    needs: python-ci # зависимость от джоба python-ci, чтобы этот джоб запускался только после успешного завершения python-ci

    steps:
      - name: Download python artifacts # шаг для скачивания артефактов с результатами тестов и покрытия кода
        uses: actions/download-artifact@v4 # шаг для скачивания артефактов с результатами тестов и покрытия кода
        with: # параметры для шага download-artifact
          name: python-artifacts # имя артефакта, который нужно скачать
          path: . # путь к директории, куда нужно скачать артефакт

      - name: Login to Docker Hub # шаг для авторизации в Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # имя пользователя для авторизации в Docker Hub, которое хранится в секретах репозитория
          password: ${{ secrets.DOCKERHUB_TOKEN }} # токен для авторизации в Docker Hub, который хранится в секретах репозитория

      - name: Build and push # шаг для сборки и публикации Docker-образа в Docker Hub
        uses: docker/build-push-action@v7
        with:
          context: ./src # путь к директории с Dockerfile. Говорит докеру где искать Dockerfile конфигурацию для сборки образа
          push: true # флаг для публикации Docker-образа в Docker Hub
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PYTHON_APP_NAME }}:${{ github.sha }} # тег для Docker-образа, который будет содержать имя пользователя, имя приложения и хэш коммита

  helm-package: # имя джоба, которое будет отображаться в UI
    if: ${{ github.ref_name == 'main' }} # условие для запуска джоба только при пуше в ветку main
    runs-on: ubuntu-latest # используемый образ для запуска джоба
    needs: python-ci # зависимость от джоба python-ci, чтобы этот джоб запускался только после успешного завершения python-ci

    steps:
      - uses: actions/checkout@v4 # шаг для клонирования репозитория в рабочую директорию
      - name: Download helm artifacts # шаг для скачивания артефактов с результатами тестов и покрытия кода
        uses: actions/download-artifact@v4 # шаг для скачивания артефактов с результатами тестов и покрытия кода
        with: # параметры для шага download-artifact
          name: helm-artifacts # имя артефакта, который нужно скачать
          path: . # путь к директории, куда нужно скачать артефакт

      - name: Set up Helm # шаг для установки Helm в рабочую директорию
        uses: azure/setup-helm@v5.0.0 # шаг для установки Helm в рабочую директорию
        with: # параметры для шага setup-helm
          version: v3.18.4 # версия Helm, которую нужно установить

      - name: Helm Lint # шаг для проверки Helm-чарта на соответствие стандартам с помощью helm lint
        run: |
          helm lint ./kube2py

      - name: Helm Template # шаг для генерации Kubernetes-манифестов из Helm-чарта с помощью helm template
        run: |
          helm template kube2py ./kube2py -f ./kube2py/values.yaml

      - name: Helm Package # шаг для упаковки Helm-чарта в tgz-архив с помощью helm package. Helm может работать только с архивами формата tgz, поэтому upload не подойдет в данном случае.
        run: |
          helm package ./kube2py --app-version ${{ github.sha }}

      - name: Upload helm package # шаг для загрузки tgz-архива с Helm-чартом в артефакты GitHub Actions
        uses: actions/upload-artifact@v4 # шаг для загрузки артефактов с результатами тестов и покрытия кода
        with: # параметры для шага upload-artifact
          name: helm-package # имя артефакта, который будет отображаться в UI
          path: |
            ./*.tgz
            ./cluster.yml

  deploy-helm-dev:
    name: Deploy Helm to Development
    uses: ./.github/workflows/deploy-workflow.yml # Путь к workflow deploy-workflow.yml(шаблон), который будет использоваться для деплоя Helm-чарта в кластер Kubernetes. В данном случае используется относительный путь к workflow, который находится в директории .github/workflows.
    needs: ["helm-package", "build-docker-image"]
    secrets: inherit # наследуем все секреты из родительского workflow
    with: # параметры для workflow deploy-workflow.yml
      environment: development # Передача параметра environment в GitHub->environment со значение development в workflow deploy-workflow.yml. В данном случае деплой будет происходить в окружение development.
      version: ${{ github.sha }}