name: Helm Upgrade
run-name: ${{ github.actor }} - ${{ github.ref_name }}
on:
  workflow_call: # триггер для запуска workflow при вызове из другого workflow. В данном случае workflow Helm Upgrade будет запускаться при вызове из workflow job=Deploy Helm to Development, который находится в директории .github/workflows/blank.yml.
    inputs: # входные параметры для workflow Helm Upgrade, которые будут передаваться из workflow job=Deploy Helm to Development
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      version:
        description: 'Version to deploy'
        required: true
        type: string
      helm-values-path:
        description: 'Path to Helm values file'
        type: string
        default: './kube2py/values.yaml'
      helm-release-name:
        description: 'Helm release name'
        type: string
        default: 'kube2py'
jobs:
  deploy-helm:
    environment: ${{ inputs.environment }} # имя окружения, в которое будет деплоиться Helm-чарт. В GitHub Actions можно создавать окружения, чтобы разграничивать деплой на разные среды (например, dev, staging, prod). В данном случае деплой будет происходить в окружение development.
    name: ${{ inputs.helm-release-name }} - Deploy Helm # имя джоба, которое будет отображаться в UI. В данном случае имя джоба будет содержать имя окружения, в которое будет деплоиться Helm-чарт.
    runs-on: ubuntu-latest  #self-hosted используемый образ для запуска джоба. В данном случае используется self-hosted runner, который настроен на локальной машине. Это позволяет использовать локальный kubectl и helm для деплоя в кластер Kubernetes.

    steps:
      - name: Download helm package
        uses: actions/download-artifact@v4
        with:
          name: helm-package
          path: .

      - name: Download helm Artifacts
        uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: .

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          config: cluster.yml

      - name: Set up Helm
        uses: azure/setup-helm@v5.0.0
        with:
          version: v3.18.4

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4

      - name: Deploy Helm to Development # шаг для деплоя Helm-чарта в кластер Kubernetes с помощью helm upgrade --install. В данном случае используется флаг --atomic, который откатывает изменения в случае ошибки, и флаг --wait, который ждет завершения деплоя перед продолжением выполнения джоба. Флаг --timeout 3600s задает таймаут ожидания деплоя в 1 час. Также используется флаг --debug, который выводит подробную информацию о деплое в логах.
        run: |
          helm upgrade --install --atomic --wait --timeout 300s --debug ${{ inputs.helm-release-name }} ./kube2py-*.tgz \
            -f ${{ inputs.helm-values-path }} \
            --set mysql.configs.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            --set mysql.configs.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
            --set mysql.configs.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
            --set kube2py.secrets.DB_CONNECTION="${{ secrets.DB_CONNECTION }}" \
            --set kube2py.secrets.password="${{ secrets.KUBE2PY_PASSWORD }}" \
            --set kube2py.secrets.login="${{ secrets.KUBE2PY_LOGIN }}" \
            --set kube2py.image.repository="${{ secrets.DOCKERHUB_USERNAME }}/kube2py" \
            --set kube2py.image.version="${{ inputs.version }}" 




